name: 'setup-docker'
runs:
  using: 'composite'
  steps:
    - uses: docker/setup-buildx-action@v2
    - uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-
